/*
Copyright (c) 2015, Plume Design Inc. All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
   3. Neither the name of the Plume Design Inc. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL Plume Design Inc. BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <sys/socket.h>
#include <sys/ioctl.h>
#include <net/if.h>
#include <arpa/inet.h>
#include <stdbool.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>

#include <errno.h>

#define LOG_MODULE_ID  LOG_MODULE_ID_OSA

#include "os.h"
#include "log.h"
#include "os_nif.h"
#include "os_types.h"
#include "util.h"
#include "ds_list.h"
#include "os_util.h"
#include "os_regex.h"
#include "os_dnsmasq.h"
#include "kconfig.h"


#define DNSMASQ_FN  "/var/etc/dnsmasq.conf"

/*
 * Start dnsmasq service (i.e. dhcp + dns cache)
 * We are not interested too much in dns cache, this will try
 * to disable
 *
 * This functions creates configuration file and then starts dnsmasq service
 */
bool os_dnsmasq_startconf(void)
{
    FILE *fconf;        /* dnsmasq config fd */
    bool retval = false;

    if (false == os_dnsmasq_stop())
    {
        LOG(ERR, "Error stopping dnsmasq service");
        return retval;
    }

    /* /var folder always exists, check if /var/etc exists, create if not */
    if (0 != mkdir("/var/etc", 755))
    {
        if (errno != EEXIST)
        {
            LOG(ERR, "/var/etc/ exists");
            return false;
        }
    }

    /* open configuration file */
    fconf = fopen(DNSMASQ_FN, "w+");

    if (NULL != fconf)
    {

        fprintf(fconf, "# auto-generated by os_dnsmasq_start\n");
        fprintf(fconf, "conf-file=/etc/dnsmasq.conf\n");
        fprintf(fconf, "dhcp-authoritative\n");
        fprintf(fconf, "domain-needed\n");
        fprintf(fconf, "localise-queries\n");
        fprintf(fconf, "read-ethers\n");
        fprintf(fconf, "bogus-priv\n");
        fprintf(fconf, "expand-hosts\n");
        fprintf(fconf, "domain=lan\n");
        fprintf(fconf, "server=/lan/\n");
        fprintf(fconf, "dhcp-leasefile=/tmp/dhcp.leases\n");
        fprintf(fconf, "resolv-file=/tmp/resolv.conf\n");
#ifdef CONFIG_TARGET_WAN_BRIDGE_NAME
        fprintf(fconf, "no-dhcp-interface=%s,eth0,eth1\n",CONFIG_TARGET_WAN_BRIDGE_NAME);
#else
        fprintf(fconf, "no-dhcp-interface=eth0,eth1\n");
#endif
        fprintf(fconf, "address=/plume.lan/192.168.1.1\n");
        fprintf(fconf, "ptr-record=1.1.168.192.in-addr.arpa,plume.lan\n");
        /*
         * Disable the default gateway and DNS server options. Cloud needs to explicitly
         * set these.
         */
        fprintf(fconf, "dhcp-option=3\n");
        fprintf(fconf, "dhcp-option=6\n");

        /* close file for write */
        fclose(fconf);

        retval = true;
    }
    else
    {
        LOG(ERR, "Error opening " DNSMASQ_FN);
    }

    return retval;
}

bool os_dnsmasq_addconf_range(
        char *ifname,
        os_ipaddr_t *start,
        os_ipaddr_t *end,
        os_ipaddr_t *netmask,
        char *lease_time_hours)
{
    bool retval = false;
    FILE *fconf;        /* dnsmasq config fd */

    /* open configuration file */
    fconf = fopen(DNSMASQ_FN, "a+");

    if (NULL != fconf)
    {
        fprintf(fconf,
                "dhcp-range=%s,"PRI_os_ipaddr_t","PRI_os_ipaddr_t","PRI_os_ipaddr_t",%s\n",
                              ifname,
                              FMT_os_ipaddr_t(*start),
                              FMT_os_ipaddr_t(*end),
                              FMT_os_ipaddr_t(*netmask),
                              lease_time_hours);

        fclose(fconf);
        retval = true;
    }
    else
    {
        LOG(ERR, "Error updating dnsmasq config file");
    }

    return retval;
}

/*
 * Add IP reservation options
 */
bool os_dnsmasq_addconf_ip_reservation(
        char *hw_addr,
        char *ip_addr,
        char *hostname)
{
    FILE *fconf = NULL;
    bool retval = false;
    int rc;

    fconf = fopen(DNSMASQ_FN, "a+");
    if (fconf == NULL)
    {
        goto error;
    }

    if (hostname != NULL && *hostname != '\0')
    {
        /* Variant with hostname */
        rc = fprintf(fconf, "dhcp-host=%s,%s,%s\n", hw_addr, hostname, ip_addr);
    }
    else
    {
        /* Variant without hostname */
        rc = fprintf(fconf, "dhcp-host=%s,%s\n", hw_addr, ip_addr);
    }

    if (rc < 0)
    {
        LOG(ERR, "Error writing dhcp-host options.");
        goto error;
    }

    retval = true;

error:
    if (fconf != NULL)
    {
        fclose(fconf);
    }

    return retval;
}

bool os_dnsmasq_addconf_opt(char *ifname, char *option)
{
    bool retval = false;
    FILE *fconf;        /* dnsmasq config fd */

    /* open configuration file */
    fconf = fopen(DNSMASQ_FN, "a+");

    if (NULL != fconf)
    {

        fprintf(fconf, "dhcp-option=%s,%s\n", ifname, option);

        fclose(fconf);
        retval = true;
    }
    else
    {
        LOG(ERR, "Error updating dnsmasq config file, option");
    }

    return retval;
}


/* stop dns configuration and actually start dnsmasq */
bool os_dnsmasq_stopconf()
{
    bool retval = false;

    /* try to start dhcp server */
#if !defined(QCA_10_4)
    if (0 == system("/usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf"))
#else
    if (0 == system("/usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -x /var/run/dnsmasq/dnsmasq.pid"))
#endif
    {
        retval = true;
    }

    return retval;
}


bool os_dnsmasq_stop(void)
{
#if !defined(QCA_10_4)
    pid_t pid = os_pid_from_file("/var/run/dnsmasq.pid");
#else
    pid_t pid = os_pid_from_file("/var/run/dnsmasq/dnsmasq.pid");
#endif

    if (pid != 0 && !os_pid_terminate(pid, 3000))
    {
        return false;
    }

    return true;
}
