#!/bin/sh -e

START=961

start()
{
    lxc-start -n opensync
}

stop()
{
    lxc-stop -n opensync
}

case "$1" in
    boot) start ;;
    start) start ;;
    stop) stop ;;
    restart) stop && start ;;
    *) exit 1 ;;
esac

